version: '3.9'
services:
  db:
    build: mysqldockerfile/.
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: master
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - mysqlcomposenetwork
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    # platform: "linux/amd64" #<-- uncomment this if you're on an M1 arm64 based chip 
  adminer:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mysqlcomposenetwork
    depends_on: 
      - db

networks: 
  mysqlcomposenetwork:
    driver: bridge
